services:
  mysql-wakanda-cultura-ocio-turismo:
    image: mysql:8.0
    hostname: mysql-wakanda-cultura-ocio-turismo
    environment:
      - MYSQL_DATABASE=Backend-Wakanda-Cultura-Ocio-Turismo
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - "3319:3306"
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-u", "root", "-pP@ssw0rd" ]
      interval: 10s
      retries: 5
      timeout: 5s

  backend-wakanda-cultura-ocio-turismo:
    build:
      context: ./
    container_name: backend-wakanda-cultura-ocio-turismo
    ports:
      - "8086:8096"
    networks:
      - backend-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-wakanda-cultura-ocio-turismo:3306/Backend-Wakanda-Cultura-Ocio-Turismo?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
    depends_on:
      mysql-wakanda-cultura-ocio-turismo:
        condition: service_healthy
    entrypoint:
      [
        "./wait-for-it.sh", "eureka-server:8761", "-t", "60", "--",
        "./wait-for-it.sh", "mysql-wakanda-cultura-ocio-turismo:3306", "-t", "60", "--",
        "java", "-jar", "/app/backend-wakanda-cultura-ocio-turismo.jar"
      ]

networks:
  backend-network:
    external: true
