spring:
  application:
    name: backend-wakanda-cultura-ocio-turismo
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8096
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
